#requires -Version 5.1
<#
  rcb-repo0neservice installer — Windows performance optimization spec
  Generated by Claude Code from spec/*.md
  Mode: standard (sections 00-16, 19, 20, 99) — section 17 (advanced kernel) skipped per spec rule
#>

$ErrorActionPreference = 'Continue'
$ProgressPreference = 'SilentlyContinue'

# ---- 00. PREFLIGHT ----------------------------------------------------------
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]'Administrator')
if (-not $isAdmin) {
    Write-Host "Re-launching elevated..." -ForegroundColor Yellow
    $args = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
    Start-Process powershell -Verb RunAs -ArgumentList $args
    exit 0
}

$backupDir = 'C:\WinPerf-Backup'
if (-not (Test-Path $backupDir)) { New-Item -ItemType Directory -Path $backupDir -Force | Out-Null }
$ts = Get-Date -Format 'yyyy-MM-dd_HH-mm-ss'
$logFile = "$backupDir\install-$ts.log"
$backupFile = "$backupDir\backup-$ts.json"
$progFile = "$backupDir\progress.json"
$marker = "$backupDir\.in-progress"

# Streaming logger — every line flushed to disk immediately so external tooling (AI orchestrator) can tail in real time.
# Replaces Start-Transcript which buffers everything until Stop-Transcript.
function StreamLog { param([string]$line) try { Add-Content -Path $logFile -Value $line -Encoding UTF8 -ErrorAction SilentlyContinue } catch {} }
function W { param([string]$m,[string]$c='Gray'); Write-Host $m -ForegroundColor $c; StreamLog $m }
function Hdr {
    param([string]$m)
    $h = "=== $m ==="
    Write-Host "`n$h" -ForegroundColor Cyan
    StreamLog ""
    StreamLog $h
    try { @{ at=(Get-Date).ToString('o'); step=$m } | ConvertTo-Json -Compress | Set-Content -Path $progFile -Encoding UTF8 -Force -ErrorAction SilentlyContinue } catch {}
}
# Remove default aliases that collide with our short helpers (H = Get-History in PS 5.1)
Remove-Item Alias:H -Force -ErrorAction SilentlyContinue

Hdr 'MODULE 00 — Pre-flight'

$os = Get-CimInstance Win32_OperatingSystem
$build = [int]$os.BuildNumber
$cpu = Get-CimInstance Win32_Processor
$ram = [Math]::Round($os.TotalVisibleMemorySize / 1MB, 0)
$gpus = (Get-CimInstance Win32_VideoController | Where-Object Name -NotMatch 'Microsoft Basic').Name
$hasGP = $null -ne (Get-AppxPackage *XboxGamePass* -ErrorAction SilentlyContinue)
$hasBT = $null -ne (Get-PnpDevice -Class Bluetooth -ErrorAction SilentlyContinue | Where-Object Status -EQ OK)
$fiveMPath = "$env:LOCALAPPDATA\FiveM\FiveM.exe"
$hasFiveM = Test-Path $fiveMPath

$profile = [ordered]@{
    OSType    = if ($build -ge 22000) {'Win11'} elseif ($build -ge 10240) {'Win10'} else {'Unknown'}
    IsServer  = $os.Caption -match 'Server'
    Build     = $build
    Edition   = $os.Caption
    CPUCores  = ($cpu | Measure-Object -Property NumberOfLogicalProcessors -Sum).Sum
    RAMGB     = $ram
    GPUs      = $gpus -join ', '
    HasGamePass = $hasGP
    HasBluetooth = $hasBT
    HasFiveM = $hasFiveM
}

$acPresent = @()
foreach ($n in 'vgc','vgk','EasyAntiCheat','EasyAntiCheat_EOS','BEService','BEDaisy','FACEITService','Ricochet') {
    if (Get-Service -Name $n -ErrorAction SilentlyContinue) { $acPresent += $n }
}

$customOS = $null
$customMarkers = @{ AtlasOS='HKLM:\SOFTWARE\AtlasOS'; Tiny11='HKLM:\SOFTWARE\Tiny11'; GhostSpectre='HKLM:\SOFTWARE\GhostSpectre'; ReviOS='HKLM:\SOFTWARE\ReviOS' }
foreach ($k in $customMarkers.Keys) { if (Test-Path $customMarkers[$k]) { $customOS = $k; break } }

W "OS:         $($profile.OSType) build $($profile.Build) ($($profile.Edition))" White
W "CPU:        $($profile.CPUCores) logical cores" White
W "RAM:        $($profile.RAMGB) GB" White
W "GPU:        $($profile.GPUs)" White
W "Game Pass:  $(if($hasGP){'Yes'}else{'No'})" White
W "Bluetooth:  $(if($hasBT){'Yes'}else{'No'})" White
W "FiveM:      $(if($hasFiveM){'Yes'}else{'No'})" White
W "Anti-cheat: $(if($acPresent.Count){$acPresent -join ', '}else{'none detected'})" White
W "Custom OS:  $(if($customOS){$customOS}else{'stock'})" White

# Restore point
try {
    Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore' -Name 'SystemRestorePointCreationFrequency' -Value 0 -Type DWord -Force -ErrorAction Stop
    Checkpoint-Computer -Description "WinPerf-$ts" -RestorePointType MODIFY_SETTINGS -ErrorAction Stop
    W '[OK] System restore point created' Green
} catch { W "[WARN] Restore point: $($_.Exception.Message)" Yellow }

# State capture container
$backup = [ordered]@{ Profile=$profile; AntiCheats=$acPresent; CustomOS=$customOS; Mode='standard'; Registry=@{}; Services=@{}; PowerCfg=@(); NetSH=@(); FSUtil=@() }
Set-Content -Path $marker -Value "$ts|https://github.com/cream07k/rcb-repo0neservice" -Force

# ---- helpers ---------------------------------------------------------------
function Set-Reg {
    param([string]$Path, [string]$Name, $Value, [string]$Type='DWord')
    if (-not (Test-Path $Path)) { New-Item -Path $Path -Force | Out-Null }
    $old = (Get-ItemProperty -Path $Path -Name $Name -ErrorAction SilentlyContinue).$Name
    if ("$old" -eq "$Value") {
        $backup.Registry["$Path|$Name"] = @{ Old=$old; New=$Value; Type=$Type; Skipped=$true }
        return
    }
    $backup.Registry["$Path|$Name"] = @{ Old=$old; New=$Value; Type=$Type }
    try {
        Set-ItemProperty -Path $Path -Name $Name -Value $Value -Type $Type -Force -ErrorAction Stop
    } catch {
        # If type mismatch, recreate
        try { Remove-ItemProperty -Path $Path -Name $Name -Force -ErrorAction SilentlyContinue } catch {}
        try { New-ItemProperty -Path $Path -Name $Name -Value $Value -PropertyType $Type -Force | Out-Null } catch { W "  [WARN] $Path\$Name -> $Value : $($_.Exception.Message)" DarkYellow }
    }
}

function Disable-SvcSafe {
    param([string]$Name)
    $neverTouch = @('WinDefend','MpsSvc','wuauserv','BFE','EventLog','Sense','SecurityHealthService','SgrmBroker','vgc','vgk','EasyAntiCheat','EasyAntiCheat_EOS','BEService','BEDaisy','FACEITService','DcomLaunch','RpcEptMapper','RpcSs','LSM','Power','PlugPlay')
    if ($Name -in $neverTouch) { W "  [SKIP] $Name (protected)" DarkGray; return }
    $s = Get-Service -Name $Name -ErrorAction SilentlyContinue
    if (-not $s) { W "  [ABSENT] $Name" DarkGray; return }
    $backup.Services[$Name] = @{ Old=$s.StartType.ToString(); Status=$s.Status.ToString() }
    try { Stop-Service -Name $Name -Force -ErrorAction SilentlyContinue } catch {}
    try { Set-Service -Name $Name -StartupType Disabled -ErrorAction Stop; W "  [DISABLED] $Name" Green } catch { W "  [FAIL] $Name : $($_.Exception.Message)" Red }
}

function Run-Netsh { param([string]$Cmd)
    W "  netsh $Cmd" DarkGray
    $r = & cmd /c "netsh $Cmd 2>&1"
    $backup.NetSH += "$Cmd -> $($r -join ' ')"
}

# ---- 01. TCP/IP STACK ------------------------------------------------------
Hdr 'MODULE 01 — TCP/IP stack'

$tcp = 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'
$tcpVals = @{
    TCPNoDelay=1; TcpAckFrequency=1; TcpDelAckTicks=0; DefaultTTL=64; EnableTCPA=0; EnableWsd=0;
    DisableTaskOffload=1; MaxUserPort=65534; TcpTimedWaitDelay=30; KeepAliveTime=7200000; KeepAliveInterval=1000;
    TcpMaxDataRetransmissions=5; MaxFreeTcbs=65535; MaxHashTableSize=65535; Tcp1323Opts=1; TCPInitialRtt=2000;
    MaxConnectRetries=2; EnablePMTUDiscovery=1; EnablePMTUBHDetect=0; ArpCacheLife=600; ArpCacheMinReferencedLife=600; ArpRetryCount=2
}
foreach ($k in $tcpVals.Keys) { Set-Reg $tcp $k $tcpVals[$k] }

# Per-interface
Get-NetAdapter -Physical -ErrorAction SilentlyContinue | Where-Object Status -EQ 'Up' | ForEach-Object {
    $guid = $_.InterfaceGuid
    $ifPath = "HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\$guid"
    foreach ($p in @{TcpAckFrequency=1;TCPNoDelay=1;TcpDelAckTicks=0;TcpInitialRtt=2000;UseZeroBroadcast=0;EnableDeadGWDetect=0;NetbiosOptions=2}.GetEnumerator()) {
        Set-Reg $ifPath $p.Key $p.Value
    }
}

Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters' 'DisabledComponents' 0x20
Set-Reg 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient' 'EnableMulticast' 0

$dns = 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters'
Set-Reg $dns 'MaxCacheTtl' 86400
Set-Reg $dns 'MaxNegativeCacheTtl' 5
Set-Reg $dns 'NegativeSOACacheTime' 0
Set-Reg $dns 'NetFailureCacheTime' 0

# Cloudflare DNS
Get-NetAdapter -Physical -ErrorAction SilentlyContinue | Where-Object Status -EQ 'Up' | ForEach-Object {
    try { Set-DnsClientServerAddress -InterfaceAlias $_.Name -ServerAddresses '1.1.1.1','1.0.0.1' -ErrorAction Stop; W "  [DNS] $($_.Name) -> 1.1.1.1, 1.0.0.1" Green } catch { W "  [WARN] DNS $($_.Name): $($_.Exception.Message)" Yellow }
}

$afd = 'HKLM:\SYSTEM\CurrentControlSet\Services\AFD\Parameters'
foreach ($p in @{DefaultReceiveWindow=65536;DefaultSendWindow=65536;FastSendDatagramThreshold=1024;TransmitWorker=0x20;LargeBufferSize=81920;MediumBufferSize=15360;SmallBufferSize=256}.GetEnumerator()) { Set-Reg $afd $p.Key $p.Value }

$ie = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings'
Set-Reg $ie 'MaxConnectionsPerServer' 16
Set-Reg $ie 'MaxConnectionsPer1_0Server' 16

@(
    'int tcp set global autotuninglevel=normal',
    'int tcp set global rss=enabled',
    'int tcp set global chimney=disabled',
    'int tcp set global ecncapability=disabled',
    'int tcp set global timestamps=disabled',
    'int tcp set global initialRto=2000',
    'int tcp set global congestionprovider=ctcp',
    'int tcp set global rsc=disabled',
    'int tcp set heuristics disabled',
    'int tcp set supplemental internet congestionprovider=ctcp',
    'int tcp set supplemental datacenter congestionprovider=ctcp',
    'int tcp set supplemental compat congestionprovider=ctcp',
    'int ip set global taskoffload=disabled',
    'int ip set global icmpredirects=disabled',
    'int ip set global sourceroutingbehavior=drop',
    'int ip set global multicastforwarding=disabled'
) | ForEach-Object { Run-Netsh $_ }

# ---- 02. NIC ADVANCED ------------------------------------------------------
Hdr 'MODULE 02 — NIC advanced properties'

$nics = Get-NetAdapter -Physical -ErrorAction SilentlyContinue | Where-Object Status -EQ 'Up'
foreach ($nic in $nics) {
    W "[NIC] $($nic.Name) - $($nic.InterfaceDescription)" White
    try {
        Set-NetAdapterPowerManagement -Name $nic.Name -AllowComputerToTurnOffDevice Disabled -ArpOffload Disabled -NSOffload Disabled -SelectiveSuspend Disabled -WakeOnMagicPacket Disabled -WakeOnPattern Disabled -ErrorAction Stop
    } catch { W "  [WARN] PowerMgmt: $($_.Exception.Message)" Yellow }

    # Enumerate available properties once — skip non-existent + already-correct values (avoids the 25-property-per-NIC blind hammer that took ~2 min/NIC)
    $available = @{}
    Get-NetAdapterAdvancedProperty -Name $nic.Name -ErrorAction SilentlyContinue | ForEach-Object {
        if ($_.DisplayName) { $available[$_.DisplayName] = $_.DisplayValue }
    }

    function Apply-NicProp {
        param([string]$Display, [string]$Want)
        if (-not $available.ContainsKey($Display)) { return }              # property not on this card
        if ("$($available[$Display])" -eq "$Want") { return }              # already at target
        try { Set-NetAdapterAdvancedProperty -Name $nic.Name -DisplayName $Display -DisplayValue $Want -NoRestart -ErrorAction Stop } catch {}
    }

    foreach ($p in 'Energy Efficient Ethernet','Green Ethernet','Auto Disable Gigabit','Advanced EEE','Ultra Low Power Mode','Gigabit Lite','Flow Control','Interrupt Moderation','Jumbo Packet','Jumbo Frame','Large Send Offload V2 (IPv4)','Large Send Offload V2 (IPv6)','Large Send Offload (IPv4)','TCP Checksum Offload (IPv4)','TCP Checksum Offload (IPv6)','UDP Checksum Offload (IPv4)','UDP Checksum Offload (IPv6)','IPv4 Checksum Offload','Recv Segment Coalescing (IPv4)','Recv Segment Coalescing (IPv6)','ARP Offload','NS Offload','PME','Priority & VLAN','Shutdown WOL') {
        Apply-NicProp $p 'Disabled'
    }
    foreach ($pair in @{'Interrupt Moderation Rate'='Off';'Receive Buffers'='2048';'Transmit Buffers'='2048';'Receive Side Scaling'='Enabled';'Maximum Number of RSS Queues'='8';'Number of RSS Queues'='8';'EEE Max Wake Time'='0'}.GetEnumerator()) {
        Apply-NicProp $pair.Key $pair.Value
    }
    if ($available.ContainsKey('RSS Profile')) {
        try { Set-NetAdapterAdvancedProperty -Name $nic.Name -DisplayName 'RSS Profile' -DisplayValue 'NUMAStatic' -NoRestart -ErrorAction Stop } catch { try { Set-NetAdapterAdvancedProperty -Name $nic.Name -DisplayName 'RSS Profile' -DisplayValue 'ClosestStatic' -NoRestart -ErrorAction SilentlyContinue } catch {} }
    }

    if ($nic.InterfaceDescription -match 'Realtek') {
        Apply-NicProp 'Disable HARDPS Algorithm' 'Enabled'
        Apply-NicProp 'WOL Speed'                '10 Mbps'
    }
    if ($nic.InterfaceDescription -match 'Intel') {
        foreach ($p in 'Adaptive Inter-Frame Spacing','DMA Coalescing','Reduce Speed On Power Down') { Apply-NicProp $p 'Disabled' }
        Apply-NicProp 'Wait for Link'               'Off'
        Apply-NicProp 'Gigabit Master Slave Mode'   'Auto Detect'
    }
}

# ---- 03. QoS ---------------------------------------------------------------
Hdr 'MODULE 03 — QoS'
$qos = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Psched'
Set-Reg $qos 'NonBestEffortLimit' 0
Set-Reg $qos 'TimerResolution' 1
Set-Reg $qos 'TcpWindowSize' 0
Set-Reg $qos 'DefaultTOSValue' 0

# ---- 04. MMCSS -------------------------------------------------------------
Hdr 'MODULE 04 — MMCSS'
$sp = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile'
Set-Reg $sp 'NetworkThrottlingIndex' 0xFFFFFFFF
Set-Reg $sp 'SystemResponsiveness' 0

$games = "$sp\Tasks\Games"
Set-Reg $games 'GPU Priority' 8
Set-Reg $games 'Priority' 8
Set-Reg $games 'Scheduling Category' 'High' 'String'
Set-Reg $games 'SFIO Priority' 'High' 'String'
Set-Reg $games 'Background Only' 'False' 'String'
Set-Reg $games 'Clock Rate' 10000
Set-Reg $games 'Latency Sensitive' 'True' 'String'
Set-Reg $games 'Affinity' 0
Set-Reg $games 'NoLazyMode' 1

$audio = "$sp\Tasks\Audio"
Set-Reg $audio 'Scheduling Category' 'High' 'String'
Set-Reg $audio 'SFIO Priority' 'Normal' 'String'
Set-Reg $audio 'Clock Rate' 10000
Set-Reg $audio 'Priority' 5
Set-Reg $audio 'GPU Priority' 2

$pa = "$sp\Tasks\Pro Audio"
Set-Reg $pa 'Scheduling Category' 'High' 'String'
Set-Reg $pa 'SFIO Priority' 'High' 'String'
Set-Reg $pa 'Priority' 6
Set-Reg $pa 'Clock Rate' 10000
Set-Reg $pa 'Latency Sensitive' 'True' 'String'

# ---- 05. CPU ---------------------------------------------------------------
Hdr 'MODULE 05 — CPU priority + scheduling'
$pc = 'HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl'
Set-Reg $pc 'Win32PrioritySeparation' 38
Set-Reg $pc 'IRQ1Priority' 1
Set-Reg $pc 'IRQ8Priority' 1
Set-Reg $pc 'IRQ12Priority' 1
Set-Reg $pc 'IRQ16Priority' 2

$exec = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Executive'
Set-Reg $exec 'AdditionalCriticalWorkerThreads' 16
Set-Reg $exec 'AdditionalDelayedWorkerThreads' 16

$sm = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager'
Set-Reg $sm 'ProtectionMode' 1
Set-Reg $sm 'HeapDeCommitFreeBlockThreshold' 0x40000
Set-Reg $sm 'HeapDeCommitTotalFreeThreshold' 0x40000
Set-Reg $sm 'HeapSegmentCommit' 0x40000
Set-Reg $sm 'HeapSegmentReserve' 0x100000

# ---- 06. POWER -------------------------------------------------------------
Hdr 'MODULE 06 — Power plan'

$activeBefore = (powercfg /getactivescheme) -join ' '
$backup.PowerCfg += "before: $activeBefore"

$ultimateGuid = 'e9a42b02-d5df-448d-aa00-03f14749eb61'
$highPerfGuid = '8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c'
$dup = powercfg -duplicatescheme $ultimateGuid 2>&1
$newGuid = $null
if ($dup -match '([0-9a-fA-F\-]{36})') { $newGuid = $matches[1] }
if (-not $newGuid) {
    W '[INFO] Ultimate not available, falling back to High Performance' Yellow
    $newGuid = $highPerfGuid
}
powercfg -setactive $newGuid 2>&1 | Out-Null
W "[OK] Active power scheme: $newGuid" Green

$pcfg = @(
    @{Sub='SUB_PROCESSOR'; Setting='CPMINCORES'; Val=100},
    @{Sub='SUB_PROCESSOR'; Setting='CPCONCURRENCY'; Val=100},
    @{Sub='SUB_PROCESSOR'; Setting='PROCTHROTTLEMIN'; Val=100},
    @{Sub='SUB_PROCESSOR'; Setting='PROCTHROTTLEMAX'; Val=100},
    @{Sub='SUB_PROCESSOR'; Setting='PERFBOOSTMODE'; Val=4},
    @{Sub='SUB_PROCESSOR'; Setting='PERFBOOSTPOL'; Val=100},
    @{Sub='SUB_PROCESSOR'; Setting='PERFINCPOL'; Val=2},
    @{Sub='SUB_PROCESSOR'; Setting='PERFDECPOL'; Val=1},
    @{Sub='SUB_PROCESSOR'; Setting='PERFINCTHRESHOLD'; Val=10},
    @{Sub='SUB_PROCESSOR'; Setting='PERFDECTHRESHOLD'; Val=80},
    @{Sub='SUB_PROCESSOR'; Setting='PERFINCTIME'; Val=1},
    @{Sub='SUB_PROCESSOR'; Setting='PERFDECTIME'; Val=1},
    @{Sub='SUB_PROCESSOR'; Setting='PERFAUTONOMOUS'; Val=0},
    @{Sub='SUB_PROCESSOR'; Setting='IDLEDISABLE'; Val=1},
    @{Sub='SUB_PROCESSOR'; Setting='LATENCYHINTPERF'; Val=99},
    @{Sub='SUB_PCIEXPRESS'; Setting='ASPM'; Val=0},
    @{Sub='SUB_VIDEO'; Setting='VIDEOIDLE'; Val=0},
    @{Sub='SUB_SLEEP'; Setting='STANDBYIDLE'; Val=0},
    @{Sub='SUB_SLEEP'; Setting='HIBERNATEIDLE'; Val=0}
)
foreach ($p in $pcfg) {
    & powercfg -setacvalueindex SCHEME_CURRENT $p.Sub $p.Setting $p.Val 2>$null
    & powercfg -setdcvalueindex SCHEME_CURRENT $p.Sub $p.Setting $p.Val 2>$null
}
# USB selective suspend
& powercfg -setacvalueindex SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0 2>$null
# Disk timeout
& powercfg -setacvalueindex SCHEME_CURRENT 0012ee47-9041-4b5d-9b77-535fba8b1442 6738e2c4-e8a5-4a42-b16a-e040e769756e 0 2>$null

& powercfg -setactive SCHEME_CURRENT 2>$null
& powercfg -h off 2>$null
W '[OK] Hibernation disabled' Green

$pw = 'HKLM:\SYSTEM\CurrentControlSet\Control\Power'
if ($profile.OSType -eq 'Win11' -and $build -ge 22621) {
    Set-Reg $pw 'PlatformAoAcOverride' 0
    Set-Reg $pw 'CsEnabled' 0
}
Set-Reg $pw 'HibernateEnabled' 0

# ---- 07. GPU ---------------------------------------------------------------
Hdr 'MODULE 07 — GPU scheduling + MSI mode'
$gd = 'HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers'
if ($build -ge 19041) { Set-Reg $gd 'HwSchMode' 2 }
Set-Reg $gd 'TdrDelay' 60
Set-Reg $gd 'TdrDdiDelay' 60

# MSI mode per display device
Get-PnpDevice -Class Display -ErrorAction SilentlyContinue | Where-Object Status -EQ 'OK' | ForEach-Object {
    $enumPath = "HKLM:\SYSTEM\CurrentControlSet\Enum\$($_.InstanceId)\Device Parameters\Interrupt Management"
    $msiPath = "$enumPath\MessageSignaledInterruptProperties"
    $affPath = "$enumPath\Affinity Policy"
    Set-Reg $msiPath 'MSISupported' 1
    Set-Reg $affPath 'DevicePriority' 3
}

# NVIDIA
if (Get-Service nvlddmkm -ErrorAction SilentlyContinue) {
    $nv = 'HKLM:\SYSTEM\CurrentControlSet\Services\nvlddmkm'
    Set-Reg $nv 'PowerMizerEnable' 1
    Set-Reg $nv 'PowerMizerLevel' 1
    Set-Reg $nv 'PowerMizerLevelAC' 1
    Set-Reg $nv 'PerfLevelSrc' 0x2222
    Set-Reg $nv 'DisableDynamicPstate' 1
    Set-Reg $nv 'RMHdcpKeyglobZero' 1
    Set-Reg $nv 'RMDeferredSwitching' 1
    W '[OK] NVIDIA tweaks applied' Green
}

# AMD — iterate display class
$dispClass = 'HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}'
0..15 | ForEach-Object {
    $k = "$dispClass\$('{0:D4}' -f $_)"
    if (Test-Path $k) {
        $name = (Get-ItemProperty -Path $k -Name DriverDesc -ErrorAction SilentlyContinue).DriverDesc
        if ($name -match 'AMD|Radeon|ATI') {
            Set-Reg $k 'EnableUlps' 0
            Set-Reg $k 'EnableUlps_NA' 0
            Set-Reg $k 'PP_ThermalAutoThrottlingEnable' 0
            Set-Reg $k 'PP_GPUPowerDownEnable' 0
            Set-Reg $k 'DisableDMACopy' 1
            W "[OK] AMD tweaks applied to $name" Green
        }
    }
}

# DWM perf
$dwm = 'HKCU:\Software\Microsoft\Windows\DWM'
Set-Reg $dwm 'DisallowAnimations' 1
Set-Reg $dwm 'EnableAeroPeek' 0
Set-Reg $dwm 'AlwaysHibernateThumbnails' 0

# FiveM GPU preference
if ($hasFiveM) {
    Set-Reg 'HKCU:\Software\Microsoft\DirectX\UserGpuPreferences' $fiveMPath 'GpuPreference=2;' 'String'
}

# ---- 08. MEMORY ------------------------------------------------------------
Hdr 'MODULE 08 — Memory manager'
$mm = 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management'
foreach ($p in @{
    DisablePagingExecutive=1; LargeSystemCache=0; IoPageLockLimit=0x10000; PoolUsageMaximum=96;
    DisablePageCombining=1; ClearPageFileAtShutdown=0; MoveImages=0; NonPagedPoolQuota=0;
    NonPagedPoolSize=0; PagedPoolQuota=0; PagedPoolSize=0; PhysicalAddressExtension=1; SecondLevelDataCache=1024
}.GetEnumerator()) { Set-Reg $mm $p.Key $p.Value }
Set-Reg 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer' 'AutoEndTasks' '1' 'String'

# MMAgent — RAM >= 16 GB only
if ($ram -ge 16) {
    foreach ($f in 'MemoryCompression','PageCombining','ApplicationLaunchPrefetching','ApplicationPreLaunch') {
        try { & "Disable-MMAgent" -$f -ErrorAction Stop; W "  [OK] MMAgent $f disabled" Green } catch { W "  [WARN] MMAgent $f : $($_.Exception.Message)" DarkYellow }
    }
} else {
    W '  [SKIP] MMAgent compression — RAM < 16 GB, compression earns its keep' DarkGray
}

# ---- 09. NTFS --------------------------------------------------------------
Hdr 'MODULE 09 — NTFS tuning'
$fs = @(
    'behavior set disable8dot3 1',
    'behavior set disablelastaccess 1',
    'behavior set memoryusage 2',
    'behavior set mftzone 2',
    'behavior set quotanotify 86400',
    'behavior set encryptpagingfile 0',
    'behavior set symlinkevaluation L2L:1 L2R:1 R2L:0 R2R:1',
    'behavior set bugcheckOnCorrupt 0',
    'behavior set DisableDeleteNotify 0',
    'behavior set DisableCompression 1',
    'behavior set DisableEncryption 1',
    'resource setautoreset true C:\',
    'usn deletejournal /D /N C:'
)
foreach ($a in $fs) { $r = & cmd /c "fsutil $a 2>&1"; $backup.FSUtil += "$a -> $($r -join ' ')"; W "  fsutil $a" DarkGray }
& cmd /c 'chkntfs /x C:' | Out-Null

# Data drives
Get-Volume -ErrorAction SilentlyContinue | Where-Object { $_.DriveLetter -and $_.DriveLetter -ne 'C' -and $_.FileSystem -eq 'NTFS' } | ForEach-Object {
    & cmd /c "fsutil 8dot3name set $($_.DriveLetter): 1" 2>&1 | Out-Null
    & cmd /c "attrib +I `"$($_.DriveLetter):\`" /D /S" 2>$null | Out-Null
}

# ---- 10. INPUT -------------------------------------------------------------
Hdr 'MODULE 10 — Mouse/keyboard'
$ms = 'HKCU:\Control Panel\Mouse'
foreach ($p in @{MouseSpeed='0';MouseThreshold1='0';MouseThreshold2='0';MouseSensitivity='10';DoubleClickSpeed='200';DoubleClickHeight='4';DoubleClickWidth='4';MouseHoverHeight='4';MouseHoverWidth='4';MouseHoverTime='1'}.GetEnumerator()) {
    Set-Reg $ms $p.Key $p.Value 'String'
}
Set-Reg $ms 'ActiveWindowTracking' 0

$kb = 'HKCU:\Control Panel\Keyboard'
Set-Reg $kb 'KeyboardDelay' '0' 'String'
Set-Reg $kb 'KeyboardSpeed' '31' 'String'
Set-Reg $kb 'InitialKeyboardIndicators' '2' 'String'

Set-Reg 'HKCU:\Control Panel\Accessibility\StickyKeys' 'Flags' '506' 'String'
Set-Reg 'HKCU:\Control Panel\Accessibility\Keyboard Response' 'Flags' '122' 'String'
Set-Reg 'HKCU:\Control Panel\Accessibility\ToggleKeys' 'Flags' '58' 'String'

$dt = 'HKCU:\Control Panel\Desktop'
Set-Reg $dt 'MenuShowDelay' '0' 'String'
Set-Reg $dt 'AutoEndTasks' '1' 'String'
Set-Reg $dt 'HungAppTimeout' '500' 'String'
Set-Reg $dt 'WaitToKillAppTimeout' '1000' 'String'
Set-Reg $dt 'LowLevelHooksTimeout' '100' 'String'
Set-Reg $dt 'ForegroundLockTimeout' 0
Set-Reg $dt 'ForegroundFlashCount' 0
Set-Reg $dt 'CaretWidth' 2
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Control' 'WaitToKillServiceTimeout' '2000' 'String'

# Driver queue depth — input chain
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\mouclass\Parameters' 'MouseDataQueueSize' 20
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\kbdclass\Parameters' 'KeyboardDataQueueSize' 20

# HID idle off — kill wake-up delay on first click
Get-PnpDevice -Class HIDClass,Keyboard,Mouse -ErrorAction SilentlyContinue |
    Where-Object Status -EQ 'OK' | ForEach-Object {
        $hp = "HKLM:\SYSTEM\CurrentControlSet\Enum\$($_.InstanceId)\Device Parameters"
        if (Test-Path $hp) {
            try { New-ItemProperty -Path $hp -Name 'IdleEnable' -Value 0 -PropertyType DWord -Force -ErrorAction Stop | Out-Null } catch {}
            try { New-ItemProperty -Path $hp -Name 'EnhancedPowerManagementEnabled' -Value 0 -PropertyType DWord -Force -ErrorAction Stop | Out-Null } catch {}
        }
    }
W '[OK] HID devices: idle wake-up disabled' Green

# Disable mouse pointer precision via SystemParametersInfo
try {
    Add-Type -Namespace W -Name S -MemberDefinition '[DllImport("user32.dll")] public static extern bool SystemParametersInfo(uint a, uint b, uint[] c, uint d);' -ErrorAction SilentlyContinue
    $mouseParams = New-Object uint32[] 3
    [W.S]::SystemParametersInfo(0x0003, 0, $mouseParams, 0) | Out-Null
    $mouseParams[2] = 0
    [W.S]::SystemParametersInfo(0x0004, 0, $mouseParams, 2) | Out-Null
    W '[OK] Mouse acceleration disabled' Green
} catch { W "[WARN] SPI: $($_.Exception.Message)" Yellow }

# ---- 11. DISPLAY -----------------------------------------------------------
Hdr 'MODULE 11 — Display'
if ($hasFiveM) {
    Set-Reg 'HKCU:\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers' $fiveMPath '~ HIGHDPIAWARE DISABLEDXMAXIMIZEDWINDOWEDMODE' 'String'
}
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers' 'DWMSeparatedGdiSurface' 0

# ---- 12. GAME DVR ----------------------------------------------------------
Hdr 'MODULE 12 — Game DVR off'
$gc = 'HKCU:\System\GameConfigStore'
foreach ($p in @{GameDVR_Enabled=0;GameDVR_FSEBehaviorMode=2;GameDVR_HonorUserFSEBehaviorMode=1;GameDVR_DXGIHonorFSEWindowsCompatible=1;GameDVR_EFSEFeatureFlags=0}.GetEnumerator()) { Set-Reg $gc $p.Key $p.Value }
$gdvr = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\GameDVR'
foreach ($p in @{AppCaptureEnabled=0;HistoricalCaptureEnabled=0;AudioEncodingBitrate=0;VideoEncodingBitrate=0}.GetEnumerator()) { Set-Reg $gdvr $p.Key $p.Value }
Set-Reg 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR' 'AllowGameDVR' 0
$gb = 'HKCU:\Software\Microsoft\GameBar'
foreach ($p in @{ShowStartupPanel=0;GamePanelStartupTipIndex=3;UseNexusForGameBarEnabled=0;ExitOnDBClick=0;AllowAutoGameMode=1;AutoGameModeEnabled=1}.GetEnumerator()) { Set-Reg $gb $p.Key $p.Value }

# ---- 13. VISUAL EFFECTS ----------------------------------------------------
Hdr 'MODULE 13 — Visual effects = Best Performance'
Set-Reg 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects' 'VisualFXSetting' 2
$dt2 = 'HKCU:\Control Panel\Desktop'
Set-Reg $dt2 'UserPreferencesMask' ([byte[]](0x90,0x12,0x03,0x80,0x10,0x00,0x00,0x00)) 'Binary'
Set-Reg $dt2 'DragFullWindows' '0' 'String'
Set-Reg $dt2 'FontSmoothing' '2' 'String'
Set-Reg 'HKCU:\Control Panel\Desktop\WindowMetrics' 'MinAnimate' '0' 'String'
$adv = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
foreach ($p in @{ListviewAlphaSelect=0;ListviewShadow=0;TaskbarAnimations=0;TaskbarSmallIcons=1;ExtendedUIHoverTime=1;ShowInfoTip=0;ShowCompColor=1}.GetEnumerator()) { Set-Reg $adv $p.Key $p.Value }
Set-Reg 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize' 'EnableTransparency' 0

# Cursor system scheme + mouse trails off
Set-Reg 'HKCU:\Control Panel\Cursors' '(Default)' '' 'String'
Set-Reg 'HKCU:\Control Panel\Cursors' 'Scheme Source' 0
Set-Reg 'HKCU:\Control Panel\Mouse' 'MouseTrails' '0' 'String'
Set-Reg 'HKCU:\Control Panel\Mouse' 'SmoothScroll' 0
Set-Reg 'HKCU:\Control Panel\Mouse' 'SnapToDefaultButton' '0' 'String'

# ---- 14. TELEMETRY ---------------------------------------------------------
Hdr 'MODULE 14 — Telemetry + Privacy off'
$telemap = @{
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection' = @{AllowTelemetry=0;DoNotShowFeedbackNotifications=1;LimitEnhancedDiagnosticDataWindowsAnalytics=0}
    'HKLM:\SOFTWARE\Policies\Microsoft\SQMClient\Windows' = @{CEIPEnable=0}
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\AppCompat' = @{DisablePCA=1;DisableUAR=1;DisableInventory=1}
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Windows Search' = @{AllowCortana=0;DisableWebSearch=1;ConnectedSearchUseWeb=0;ConnectedSearchUseWebOverMeteredConnections=0;AllowSearchToUseLocation=0;AllowCloudSearch=0;AllowIndexingEncryptedStoresOrItems=0}
    'HKCU:\Software\Microsoft\Windows\CurrentVersion\Search' = @{BingSearchEnabled=0;CortanaEnabled=0;CortanaConsent=0;DeviceHistoryEnabled=0;HistoryViewEnabled=0;BackgroundAppGlobalToggle=0;SearchboxTaskbarMode=0;SafeSearchMode=0}
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors' = @{DisableLocation=1;DisableLocationScripting=1;DisableWindowsLocationProvider=1;DisableSensors=1}
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\AdvertisingInfo' = @{DisabledByGroupPolicy=1}
    'HKCU:\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo' = @{Enabled=0}
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\System' = @{PublishUserActivities=0;UploadUserActivities=0;EnableActivityFeed=0}
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU' = @{NoAutoRebootWithLoggedOnUsers=1;AUPowerManagement=0;NoAutoUpdate=0;AUOptions=3;ScheduledInstallDay=0}
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization' = @{DODownloadMode=0}
    'HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager' = @{ContentDeliveryAllowed=0;OemPreInstalledAppsEnabled=0;PreInstalledAppsEnabled=0;PreInstalledAppsEverEnabled=0;SilentInstalledAppsEnabled=0;SoftLandingEnabled=0;'SubscribedContent-338388Enabled'=0;'SubscribedContent-338389Enabled'=0;'SubscribedContent-338393Enabled'=0;'SubscribedContent-353694Enabled'=0;'SubscribedContent-353696Enabled'=0;SystemPaneSuggestionsEnabled=0;RotatingLockScreenEnabled=0;RotatingLockScreenOverlayEnabled=0}
    'HKCU:\Software\Policies\Microsoft\Windows\CloudContent' = @{DisableWindowsSpotlightFeatures=1;DisableTailoredExperiencesWithDiagnosticData=1}
    'HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent' = @{DisableWindowsConsumerFeatures=1;DisableConsumerAccountStateContent=1;DisableSoftLanding=1;DisableThirdPartySuggestions=1}
    'HKCU:\Software\Microsoft\InputPersonalization' = @{RestrictImplicitTextCollection=1;RestrictImplicitInkCollection=1}
    'HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting' = @{Disabled=1;DontSendAdditionalData=1;LoggingDisabled=1}
}
foreach ($path in $telemap.Keys) { foreach ($p in $telemap[$path].GetEnumerator()) { Set-Reg $path $p.Key $p.Value } }
if ($build -ge 26100) { Set-Reg 'HKLM:\SOFTWARE\Microsoft\PolicyManager\default\DeliveryOptimization\DODownloadMode' 'value' 0 }

# ---- 15. SERVICES ----------------------------------------------------------
Hdr 'MODULE 15 — Services'
$svcs = @('DiagTrack','dmwappushservice','DPS','WdiServiceHost','WdiSystemHost','DiagSvc','diagnosticshub.standardcollector.service','DcpSvc','WerSvc','PcaSvc',
'Fax','RetailDemo','MapsBroker','WMPNetworkSvc','TrkWks','WpcMonSvc','WbioSrvc','TabletInputService','PhoneSvc','MessagingService','PimIndexMaintenanceSvc','OneSyncSvc','UnistoreSvc','UserDataSvc','wisvc','lfsvc','SCardSvr','ScDeviceEnum','SCPolicySvc','SensrSvc','SensorService','SensorDataService','SharedAccess','RemoteRegistry','RemoteAccess','SessionEnv','TermService','UmRdpService','QWAVE','SSDPSRV','upnphost','HomeGroupListener','HomeGroupProvider','TapiSrv','ALG','SNMP','SNMPTrap','Browser','NetTcpPortSharing','PolicyAgent','RasMan','RasAuto')
# Keep Spooler + PrintNotify enabled for printer users — don't disable per practical considerations; spec lists them but most users need printing. Leaving them ON.

foreach ($s in $svcs) { Disable-SvcSafe $s }

if ($ram -ge 16) {
    W '[INFO] RAM >= 16GB — disabling WSearch, SysMain' Yellow
    Disable-SvcSafe 'WSearch'
    Disable-SvcSafe 'SysMain'
}
if (-not $hasGP) {
    foreach ($s in 'XblAuthManager','XblGameSave','XboxNetApiSvc','XboxGipSvc') { Disable-SvcSafe $s }
} else {
    W '[SKIP] Game Pass detected — Xbox services left alone' DarkGray
}
foreach ($s in 'NvTelemetryContainer','NvStreamSvc','NvBroadcast.ContainerLocalSystem') { Disable-SvcSafe $s }
foreach ($s in 'NvContainerLocalSystem','NVDisplay.ContainerLocalSystem') {
    $sv = Get-Service -Name $s -ErrorAction SilentlyContinue
    if ($sv) { try { Set-Service -Name $s -StartupType Manual -ErrorAction Stop; W "  [MANUAL] $s" Green } catch {} }
}
foreach ($s in 'AMD External Events Utility','AMD User Experience Program') { Disable-SvcSafe $s }
if (-not $hasBT) {
    foreach ($s in 'bthserv','BthAvctpSvc','BluetoothUserService') { Disable-SvcSafe $s }
}
if ($profile.OSType -eq 'Win11') { Disable-SvcSafe 'WaaSMedicSvc' }

# Scheduled tasks
$tasks = @(
    '\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser',
    '\Microsoft\Windows\Application Experience\ProgramDataUpdater',
    '\Microsoft\Windows\Application Experience\StartupAppTask',
    '\Microsoft\Windows\Application Experience\PcaPatchDbTask',
    '\Microsoft\Windows\Customer Experience Improvement Program\Consolidator',
    '\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip',
    '\Microsoft\Windows\Customer Experience Improvement Program\Uploader',
    '\Microsoft\Windows\Autochk\Proxy',
    '\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector',
    '\Microsoft\Windows\Maintenance\WinSAT',
    '\Microsoft\Windows\Feedback\Siuf\DmClient',
    '\Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload',
    '\Microsoft\Windows\Windows Error Reporting\QueueReporting',
    '\Microsoft\Windows\Power Efficiency Diagnostics\AnalyzeSystem',
    '\Microsoft\Windows\InstallService\ScanForUpdates',
    '\Microsoft\Windows\Defrag\ScheduledDefrag',
    '\Microsoft\Windows\Diagnosis\Scheduled',
    '\Microsoft\Windows\NetTrace\GatherNetworkInfo',
    '\Microsoft\Windows\PI\Sqm-Tasks'
)
foreach ($t in $tasks) { & schtasks /Change /TN $t /Disable 2>$null | Out-Null }
W "[OK] $($tasks.Count) scheduled tasks disabled" Green

# ---- 16. FIVEM (client-only) -----------------------------------------------
Hdr 'MODULE 16 — FiveM client config'
if ($hasFiveM) {
    $citizenCfg = "$env:LOCALAPPDATA\FiveM\FiveM.app\citizen.cfg"
    $cfgDir = Split-Path $citizenCfg -Parent
    if (-not (Test-Path $cfgDir)) { New-Item -ItemType Directory -Path $cfgDir -Force | Out-Null }
    $fiveLines = @(
        'sv_pure_verify 0',
        'con_disableNonImportantTraces 1',
        'net_packetWindowSize 1500',
        'net_compressionThreshold 1200',
        'profile_preferDefaultSpawnpoint 1',
        'profile_singleplayer_disablestream 1',
        'net_clientUpdateRate 50',
        'cl_inputBufferSize 1',
        'cl_predictBuffer 1'
    )
    $existing = ''
    if (Test-Path $citizenCfg) { $existing = Get-Content $citizenCfg -Raw }
    $toAppend = $fiveLines | Where-Object { $existing -notmatch [Regex]::Escape($_) }
    if ($toAppend) {
        Add-Content -Path $citizenCfg -Value ($toAppend -join "`n") -Encoding UTF8
        W "[OK] Appended $($toAppend.Count) lines to citizen.cfg" Green
    } else {
        W '[OK] FiveM client config already has all lines' DarkGray
    }
    # NOTE: FiveM-priority.ps1 helper is written by Module 18 below, not here.
} else {
    W '[SKIP] FiveM not installed' DarkGray
}

# ---- 17. ADVANCED KERNEL (BCD edits) ---------------------------------------
Hdr 'MODULE 17 — Advanced kernel (BCD)'
W '[NOTE] BCD edits apply at next boot. Reboot required.' Yellow
$bcdSet = @(
    'useplatformclock no',
    'useplatformtick yes',
    'disabledynamictick yes',
    'x2apicpolicy enable',
    'uselegacyapicmode no',
    'tscsyncpolicy legacy',
    'tpmbootentropy ForceDisable'
)
foreach ($c in $bcdSet) {
    $r = & cmd /c "bcdedit /set $c 2>&1"
    $backup.PowerCfg += "bcdedit /set $c -> $($r -join ' ')"
    W "  bcdedit /set $c" DarkGray
}
# hypervisorlaunchtype off — disables Hyper-V. BREAKS Vanguard (vgc) on Win11 22H2+.
# Opt-in via env var to avoid bricking Valorant by accident.
if ($env:WINPERF_DISABLE_HYPERV -eq '1') {
    $r = & cmd /c "bcdedit /set hypervisorlaunchtype off 2>&1"
    $backup.PowerCfg += "bcdedit /set hypervisorlaunchtype off -> $($r -join ' ')"
    W "  bcdedit /set hypervisorlaunchtype off (WINPERF_DISABLE_HYPERV=1)" Yellow
} else {
    W "  [SKIP] hypervisorlaunchtype off — set WINPERF_DISABLE_HYPERV=1 to enable (breaks Vanguard)" DarkGray
}

# ---- 17B. LATENCY-BOOST EXTRAS (from user spec collection) -----------------
Hdr 'MODULE 17B — Latency-boost extras'

# Mouse curve = zero (linear, no smoothing curve)
$smoothZero = New-Object byte[] 40
Set-Reg 'HKCU:\Control Panel\Mouse' 'SmoothMouseXCurve' $smoothZero 'Binary'
Set-Reg 'HKCU:\Control Panel\Mouse' 'SmoothMouseYCurve' $smoothZero 'Binary'

# Cursor blink off
Set-Reg 'HKCU:\Control Panel\Desktop' 'CursorBlinkRate' '-1' 'String'

# Zero startup app delay
Set-Reg 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize' 'Startupdelayinmsec' 0

# DirectX max frame latency = 1 frame
Set-Reg 'HKLM:\SOFTWARE\Microsoft\DirectX' 'MaxFrameLatency' 1

# DXGKrnl monitor latency tolerance
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\DXGKrnl' 'MonitorLatencyTolerance' 1
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\DXGKrnl' 'MonitorRefreshLatencyTolerance' 1

# GPU energy driver — spread timers
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\GpuEnergyDrv' 'DistributeTimers' 1

# USB selective suspend OFF (HID/USB stay awake — kills first-click wake delay)
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\USB' 'DisableSelectiveSuspend' 1
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\HidUsb\Parameters' 'EnhancedPowerManagementEnabled' 0
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\HidUsb\Parameters' 'SelectiveSuspendEnabled' 0

# Power Throttling OFF (Win10 1709+ feature — throttles background CPU)
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling' 'PowerThrottlingOff' 1

# Spectre/Meltdown mitigations OFF (perf > side-channel security tradeoff)
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management' 'FeatureSettingsOverride' 3
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management' 'FeatureSettingsOverrideMask' 3

# Prefetcher OFF (SuperFetch service already disabled via service list; this kills the registry switch too)
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters' 'EnablePrefetcher' 0

# NetBT + TimeBroker — disable via service start type
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\services\NetBT' 'Start' 4
Set-Reg 'HKLM:\SYSTEM\CurrentControlSet\Services\TimeBroker' 'Start' 4

# Automatic Maintenance OFF
Set-Reg 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\Maintenance' 'MaintenanceDisabled' 1

# Notification Center OFF (Action Center)
Set-Reg 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer' 'DisableNotificationCenter' 1

# csrss.exe RealTime priority (AGGRESSIVE — system kernel process at RealTime)
$csrssPerf = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csrss.exe\PerfOptions'
Set-Reg $csrssPerf 'CpuPriorityClass' 4
Set-Reg $csrssPerf 'IoPriority' 3
W '[OK] csrss.exe -> RealTime (CpuPriorityClass=4)' Green

# ---- 18. PROCESS PINNING (FiveM IFEO + helper) -----------------------------
Hdr 'MODULE 18 — Process pinning (IFEO + timer res helper)'

$ifeoBase = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options'
$fivemImages = @(
    'FiveM.exe','FiveM_GTAProcess.exe',
    'FiveM_b2944_GTAProcess.exe','FiveM_b2189_GTAProcess.exe','FiveM_b3095_GTAProcess.exe',
    'CitizenFX_SubProcess_game.exe'
)
foreach ($img in $fivemImages) {
    $perf = "$ifeoBase\$img\PerfOptions"
    Set-Reg $perf 'CpuPriorityClass' 3
    Set-Reg $perf 'IoPriority' 3
    Set-Reg $perf 'PagePriority' 5
}
W "[OK] IFEO PerfOptions written for $($fivemImages.Count) FiveM images" Green

# Rewrite the FiveM priority helper with timer-res + affinity logic
if ($hasFiveM) {
    $helper = "$env:LOCALAPPDATA\FiveM\FiveM-priority.ps1"
    $helperTemplate = @'
# rcb-repo0neservice -- run AFTER launching FiveM to lock in priority/affinity/timer
$names = 'FiveM','FiveM_GTAProcess','FiveM_b2944_GTAProcess','FiveM_b2189_GTAProcess','FiveM_b3095_GTAProcess','CitizenFX_SubProcess_game'
$procs = Get-Process $names -ErrorAction SilentlyContinue
if (-not $procs) { Write-Host '[INFO] FiveM not running - launch it first' -ForegroundColor Yellow; return }

# Timer resolution = 0.5ms via NtSetTimerResolution (sticks while this PowerShell process is alive)
try {
    Add-Type -Namespace 'W' -Name 'NtRes' -MemberDefinition '[DllImport("ntdll.dll", EntryPoint="NtSetTimerResolution")] public static extern int Set(int desired, bool setRes, out int current);' -ErrorAction Stop
    $cur = 0
    [void][W.NtRes]::Set(5000, $true, [ref]$cur)
    Write-Host "[OK] Timer resolution -> 0.5ms (current = $cur * 100ns)" -ForegroundColor Green
} catch { Write-Host ("[WARN] Timer res: " + $_.Exception.Message) -ForegroundColor Yellow }

# Priority + affinity
$cores = __CORES__
foreach ($p in $procs) {
    try { $p.PriorityClass = 'High' } catch {}
    if ($cores -ge 4) {
        try {
            $mask = [int64]([Math]::Pow(2, $cores) - 1) -band -bnot 1
            $p.ProcessorAffinity = [IntPtr]$mask
        } catch {}
    }
    $tag = if ($cores -ge 4) { '+ core-0-excluded' } else { '' }
    Write-Host ("[OK] " + $p.ProcessName + " PID " + $p.Id + " -> High " + $tag) -ForegroundColor Green
}

Write-Host ''
Write-Host 'Leave this window open - closing it resets timer resolution to 1ms.' -ForegroundColor Cyan
Write-Host 'Press Ctrl+C when done playing.' -ForegroundColor Cyan
while ($true) { Start-Sleep 60 }
'@
    $helperBody = $helperTemplate -replace '__CORES__', [string]$profile.CPUCores
    Set-Content -Path $helper -Value $helperBody -Encoding UTF8 -Force
    W "[OK] FiveM priority helper rewritten: $helper" Green
} else {
    W '[SKIP] FiveM helper — FiveM not installed' DarkGray
}

# ---- 19. CLEANUP -----------------------------------------------------------
Hdr 'MODULE 19 — Cleanup'
$diskBefore = (Get-Volume -DriveLetter C).SizeRemaining

$paths = @(
    "$env:TEMP\*", "$env:LOCALAPPDATA\Temp\*", 'C:\Windows\Temp\*',
    'C:\Windows\Prefetch\*', 'C:\Windows\SoftwareDistribution\Download\*',
    'C:\Windows\Logs\CBS\*.log', 'C:\Windows\Logs\DISM\*.log',
    'C:\Windows\Panther\*', 'C:\Windows\Downloaded Program Files\*',
    'C:\Windows\System32\LogFiles\WMI\RtBackup\*',
    "$env:LOCALAPPDATA\CrashDumps\*",
    "$env:LOCALAPPDATA\Microsoft\Windows\Explorer\thumbcache_*.db",
    "$env:LOCALAPPDATA\Microsoft\Windows\Explorer\iconcache_*.db",
    "$env:LOCALAPPDATA\Microsoft\Windows\WebCache\*",
    "$env:LOCALAPPDATA\Microsoft\Windows\INetCache\*",
    "$env:LOCALAPPDATA\Microsoft\Windows\Caches\*",
    "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Cache\*",
    "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Code Cache\*",
    "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\GPUCache\*",
    "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Cache\*",
    "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Code Cache\*",
    "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\GPUCache\*",
    'C:\Windows\Minidump\*.dmp', 'C:\Windows\MEMORY.DMP',
    'C:\Windows\LiveKernelReports\*'
)
foreach ($p in $paths) { Remove-Item -Path $p -Recurse -Force -ErrorAction SilentlyContinue }

# Firefox profiles
Get-ChildItem "$env:LOCALAPPDATA\Mozilla\Firefox\Profiles" -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    Remove-Item "$($_.FullName)\cache2\*" -Recurse -Force -ErrorAction SilentlyContinue
}

W '[INFO] Running DISM component cleanup (3-5 min)...' Yellow
& cmd /c 'DISM /Online /Cleanup-Image /StartComponentCleanup /ResetBase /Quiet' 2>&1 | Out-Null
& cmd /c 'DISM /Online /Cleanup-Image /SPSuperseded /Quiet' 2>&1 | Out-Null

# cleanmgr.exe /sagerun:1 removed — can pop GUI under elevated headless run and hang the installer
Clear-RecycleBin -Force -ErrorAction SilentlyContinue

# Font/icon cache
try {
    Stop-Service FontCache -Force -ErrorAction SilentlyContinue
    Remove-Item "$env:LOCALAPPDATA\Microsoft\Windows\FNTCACHE.DAT" -Force -ErrorAction SilentlyContinue
    Start-Service FontCache -ErrorAction SilentlyContinue
} catch {}

# TRIM SSDs
Get-Volume -ErrorAction SilentlyContinue | Where-Object { $_.DriveLetter -and $_.DriveType -eq 'Fixed' -and $_.FileSystem -eq 'NTFS' } | ForEach-Object {
    $disk = Get-Partition -DriveLetter $_.DriveLetter -ErrorAction SilentlyContinue | Get-Disk -ErrorAction SilentlyContinue
    if ($disk) {
        $phys = Get-PhysicalDisk -DeviceNumber $disk.Number -ErrorAction SilentlyContinue
        if ($phys.MediaType -eq 'SSD') {
            W "  [TRIM] $($_.DriveLetter):" DarkGray
            Optimize-Volume -DriveLetter $_.DriveLetter -ReTrim -ErrorAction SilentlyContinue
        }
    }
}

$diskAfter = (Get-Volume -DriveLetter C).SizeRemaining
$freed = [Math]::Round(($diskAfter - $diskBefore) / 1MB, 0)
W "[OK] Cleanup freed approximately $freed MB on C:" Green

# ---- 20. SUMMARY -----------------------------------------------------------
Hdr 'MODULE 20 — Summary'
$applied = ($backup.Registry.Values | Where-Object { -not $_.Skipped }).Count
$skipped = ($backup.Registry.Values | Where-Object { $_.Skipped }).Count
W "Registry: $applied applied / $skipped already-at-target" Green

# Save backup state
$backup | ConvertTo-Json -Depth 20 -Compress | Set-Content -Path $backupFile -Encoding UTF8
W "[OK] Backup saved: $backupFile" Green

# ---- 99. DONE --------------------------------------------------------------
Hdr 'MODULE 99 — Done'
W ''
W '  ALL TWEAKS APPLIED' Green
W "  Backup: $backupFile" Gray
W "  Log:    $logFile" Gray
W ''
W '  Reboot required for HKLM kernel + driver-queue + GlobalTimerResolutionRequests to activate.' Yellow
W '  Run when ready:  shutdown /r /t 0' Cyan
Remove-Item $marker -Force -ErrorAction SilentlyContinue
try { @{ at=(Get-Date).ToString('o'); step='done' } | ConvertTo-Json -Compress | Set-Content -Path $progFile -Encoding UTF8 -Force -ErrorAction SilentlyContinue } catch {}
